### ISSUE TITLE
Are we prepared to Jessie?

### ISSUE THREAD

**Issue by JulianVolodia** [deimosfr/packer-debian#1]
Hi, could you say if you were trying to build Jessie package with success?

E.g. ansible.sh have hardcoded wheezy... 

> if [ $(facter lsbdistcodename) = 'wheezy' ] ;

Also, I haven't seen any Jessie package here: https://vagrantcloud.com/deimosfr/debian-wheezy

Regards, jv.

**Comment by JulianVolodia** [comment]
More on my fork of this repo. (branch: master)

**Comment by deimosfr** [comment]
Hi,

I wasn't trying to build jessie packages but using backports packages for jessie as it's not in the main repository. However in Jessie, it is ! That's why depending on the distribution, I use backports or not.

**Comment by JulianVolodia** [comment]
Thanks, but it was more than 1 year ago :) I think we could close that ;)

Best regards.
