### ISSUE TITLE
"facter: command not found" warnings

### ISSUE THREAD

**Issue by JulianVolodia** [deimosfr/packer-debian#2]
==> virtualbox-iso: Provisioning with shell script: scripts/jessie/networking.sh
    virtualbox-iso: [sudo] password for vagrant: /tmp/script.sh: line 3: facter: command not found
    virtualbox-iso: /tmp/script.sh: line 3: [: =: unary operator expected

...

==> virtualbox-iso: Provisioning with shell script: scripts/jessie/puppet.sh
    virtualbox-iso: /tmp/script.sh: line 3: facter: command not found
    virtualbox-iso: /tmp/script.sh: line 3: [: =: unary operator expected

---

Probably `facter` not installed. Only mentioned in ansible.sh which not execute.

**Comment by deimosfr** [comment]
Hi,

Sorry for the late answer. Do you still got the issue ?

**Comment by JulianVolodia** [comment]
Thanks! I did not noticed...
